version: '3'

volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: docker.io/library/postgres:latest
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: Passw0rd
    ports:
      - 5432:5432
  keycloak:
    build: .
    restart: unless-stopped
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres 
    ports:
      - 8443:8443
      - 8080:8080
    depends_on:
      - postgres