version: '3'

volumes:
  postgres_data:
      driver: local

services:
  postgres:
      image: postgres:latest
      volumes:
        - postgres_data:/var/lib/postgresql/data
      environment:
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: Passw0rd
  keycloak:
      image: quay.io/keycloak/keycloak:latest
      environment:
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
      ports:
        - 8085:8080
        - 8445:8443
      depends_on:
        - postgres
      command: start-dev --db-url-host postgres --db-username keycloak --db-password Passw0rd